import Head from 'next/head';

import classes from '../styles/Home.module.scss';
import Header from '@/components/Home/Header/Header';
import MainNavigation from '@/components/UI/MainNavigation/MainNavigation';
import Categories from '@/components/Home/Categories/Categories';

import { useSelector } from 'react-redux';

export default function Home() {
  const {darkTheme} = useSelector(state => state.user);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainNavigation page='home' />
      <Header />

      <main className={`${classes.main} ${darkTheme ? 'dark' : ''}`}>
        <Categories />
      </main>
    </>
  );
}
